#!/bin/bash

#SBATCH --partition=gpu_mig
#SBATCH --gpus=1
#SBATCH --job-name=MinimalRunSwAV
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=01:00:00
#SBATCH --output=job_outputs/slurm_output_%A.out

module purge
module load 2024
module load Anaconda3/2024.06-1

cd $HOME/ssl-ecg-quality/
source activate ecg

srun python -u custom_swav_bolts.py --batch_size 512 --epochs 1 --precision 16 --trafos RandomResizedCrop --log_dir=experiment_logs --gpus=1